### ISSUE TITLE
Malicious site block has no "let me in anyway"

### ISSUE THREAD

**Issue by BlueHatbRit** [PalmerAL/min#13]
I'm trying to access a local site that we're using for a CI server but I'm met with the malicious warning screen. Sadly it seems there's no option other than "leave this site". I'm wondering if there's something I'm missing here?

**Comment by LouWii** [comment]
There shouldn't be the malicious error message when I try to access my own local dev sites
(url is http://devsite.dev/system/ ).

**Comment by idle-zealot** [comment]
My university WiFi requires that I be redirected to a login page, but whenever the redirect triggers I get taken to that warning screen. There really ought to be an option to proceed.

**Comment by PalmerAL** [comment]
Maybe this should just be a bar across the top of the screen, with an icon to close it?

**Comment by idle-zealot** [comment]
I know chrome has a full screen warning, much like the current one in Min, but with an out of the way button so that power users can bypass it. The full screen warning is really just for the sake of less tech savvy users, so if you plan to cater to that demographic, keeping the warning screen big and scary may be wis.

**Comment by PalmerAL** [comment]
I've added a button to bypass the phishing warnings in 4212602cd3c841ed8888f20482bc3f68c2dc8f84.

It looks like this:

<img width="789" alt="screen shot 2016-04-21" src="https://cloud.githubusercontent.com/assets/10314059/14726445/06825ff4-07e8-11e6-8b6f-10daa67c0d49.png">

Once clicked, all pages on that domain are whitelisted, so you won't see the phishing warning.

The fix for this will be included in 1.2.0. I was originally planning to release that a week from now, but I may release it this weekend if I have time.
