### ISSUE TITLE
Release 1.2.1 with 1.2.0 builds

### ISSUE THREAD

**Issue by valtlfelipe** [PalmerAL/min#132]
Just downloaded the new version from the releases page(https://github.com/PalmerAL/min/releases/tag/v1.2.1) and, at least on OS X, I got the version 1.2.0 when running.
![captura de tela 2016-05-07 as 15 31 19](https://cloud.githubusercontent.com/assets/3065339/15093812/c8e38262-1468-11e6-8197-ef303f14638e.png)

**Comment by PalmerAL** [comment]
It's because I forgot to update the version field of the package.json. It is actually a 1.2.1 build, it just has the wrong version number.

I think Github allows releases to be edited, so I can try to re-build with the correct version number.

**Comment by valtlfelipe** [comment]
The build that I just downloaded does not appear to have the fix that I made on PR #121 or there is a bug.

**Comment by PalmerAL** [comment]
Hmmmm, it doesn't. I wonder if I didn't sync the local copy of the repository with the remote copy before building the release? It was definitely merged, so I'm not sure how else it could have been left out.

**Comment by valtlfelipe** [comment]
Strange... I inspected the package content of the .app on OS X, and infact the code that I added is not there. Have you checked that the other fixes in this release are present in this build? Maybe rebuilding the app could fix it?

**Comment by PalmerAL** [comment]
The other fixes are all there (you can confirm by opening a lot of tabs, and checking that the scrollbar looks the same as in #76). I think what happened is that I merged your pull request, then built the builds, but didn't sync with the remote repository first, so that the changes weren't on my computer when the builds were built.

I think rather than rebuilding 1.2.1 I'll release a 1.2.2 tomorrow. That way, the other issue mentioned above (with the incorrect version number) can also be fixed.

**Comment by valtlfelipe** [comment]
Makes sense! Ok, thanks

**Comment by PalmerAL** [comment]
I've released 1.2.2, and I've verified that it includes #121 this time.
