### ISSUE TITLE
Add tab tree structure

### ISSUE THREAD

**Issue by 0xdec** [PalmerAL/min#5]
I would love to see support for a tree tab structure, similar to that of tree-style-tab for Firefox. Preliminarily, I could see a horizontal tab tree working as follows:
- the tab bar shows the current tab as well as all of its siblings, side-by-side
- a key combination can be used to move up and down the tree, e.g. ctrl-up & ctrl-down
- when cmd-shift-e is pressed, the current tab and its siblings stay in their positions, but an additional tab bar containing all the children of the current tab appears below. These children should update based on which tab is currently selected. Moving up in the tab tree selects the current tab's parent, and the tab bar now displays the parent and all of its siblings.

A vertical tab bar would also be useful, but is somewhat less so on normal 16:9 screens, especially considering that many sites are optimized for this aspect ratio. I'm quite busy with classes this semester, but I would love to contribute to min in some way when time allows. Maybe I'll start trying to tackle tree tabs.

I didn't want to clutter up the text of this issue, but I want to say how impressed I am with this project. I am astounded by the sheer number of commits you have made, especially considering that you are working alone. I use DuckDuckGo on all of my machines, and the tight integration between DDG and min is ridiculously awesome. This project deserves so many more stars, and I'm definitely going to tell my friends about it. Keep up the great work, and I'll definitely keep an eye on how min is progressing!

**Comment by PalmerAL** [comment]
What’s the main benefit of tree-style tabs? I don’t use them myself so I’m wondering:

* Are they useful as a visual thing, where you can quickly see how your tabs are related? 
* Or is the benefit that it makes navigating around the tabstrip using keyboard shortcuts easier?

I'm wondering if this is something that should be built into expanded tab mode, rather than the regular tabstrip. It seems like it would be difficult to keep the regular tabstrip simple, while also making it work with large trees of tabs.

**Comment by D1SC0tech** [comment]
I often have hundreds of tabs open, organized into separate windows by project. I find that I can't really have any more than 20 or so tabs in a window before it becomes impossible to both read the tab titles and navigate to different tabs. A vertical tab bar solves the first problem because each tab takes up much less vertical space than horizontal. A tree structure solves the second problem, because it allows me to group tabs in ways that make sense to me.

For example, one of my windows currently has around 100 tabs, but only ~20 top-level tabs. The tabs are all distinct from each other but have related tabs as children. E.g. one is the MDN reference for RegExp, and its children are several other tabs about regexes. Another is the reference for the SVG coordinate system. Its children are various other SVG references and other similar tabs.

But yeah, I think it would do best in just expanded tab mode. The regular tabstrip can just show the current tab and its siblings, as usual.

**Comment by PalmerAL** [comment]
Have you tried Firefox's tab groups feature?

It sounds like multiple levels of nesting aren't important (are they?).

If that's true, Min could have something like tab groups. Expanded tab mode could show all the groups, and the tab bar would only show the tabs in the current group (like Firefox). The expanded tab mode would also have a button to create a new group, and would allow dragging tabs between groups, dragging a tab into a new group, etc. To use your example, you could have a group with all the regex-related tabs, and a group with all of the SVG-related tabs.

Benefits:

* Unlike a true tree-style system, it doesn't interrupt the normal tab mode - if you never open expanded mode, tabs will work just like they currently do.
* Easier to visualize than tree-style tabs.

The downside would be that there can only be one level of tab nesting.

The expanded tab mode UI could work in a couple of different ways:

* Tiles for each tab (like the current expanded mode). Each tab set would take up the full width of the screen, and expand to 3-5 rows vertically before scrolling horizontally.
* Tab groups would be arranged in columns, like a vertical tab list.

**Comment by PalmerAL** [comment]
I've started working on this in the [tasks-overlay](https://github.com/PalmerAL/min/tree/tasks-overlay) branch.

The regular tabstrip only shows tabs for the current task. I've moved expanded tab mode into an overlay, which shows all open tasks, and also allows you to name tasks, delete tasks, etc.

I would love some feedback on this. How well does this work? What could be improved about it?

There is a binary for OS X here: https://github.com/PalmerAL/min/releases/download/v1.1.0-alpha1/Min-v1.1.0-alpha1.zip. Let me know if you would like Windows or Linux binaries to test as well.

**Comment by D1SC0tech** [comment]
Hey, I just downloaded the new release, it looks great! Sorry I took so long to respond, the notification email seems to have fallen through the cracks.

I used Firefox's tab groups for a while, but they removed it as of FF45, or somewhere around there. As for the tree layout, what I was thinking of wouldn't disrupt normal usage either. It would function similarly to how you have it now, except that each task could contain subtasks. Either way, only the top-level tabs of the current task would show up in the tab bar. As for whether it's actually needed, I'm going to start using Min regularly and see if I miss a true tree.

My preliminary thought is that a tree is useful for having grouped tabs inside of tasks, e.g. you could have a "SVG reference" task with several general tabs, as well as sub-trees for SVG elements and SVG styling, which each have tabs related to those specific topics. For people who don't use this feature, nothing should change in terms of usage or visualization.

I use Arch on my desktop machine, but if it's as easy "npm install && grunt" then I won't ask you to compile a binary. Again, sorry about the lateness, I'm still pretty busy but I'll definitely test it out and give some feedback.

**Comment by D1SC0tech** [comment]
Just had to add this: holy crap, Min is polished. I am in awe of the work you've put into it, it honestly feels like an app made by a much larger team.

**Comment by PalmerAL** [comment]
@D1SC0tech What do you think? This branch includes some pretty major changes to the data model, so I'd like to decide whether to merge this or not. Its difficult to change a lot of parts of the browser without creating merge conflicts.

**Comment by D1SC0tech** [comment]
I'd say merge. I've been using Min for non-critical things for the past couple of weeks, and the Tasks model works really well.
