### ISSUE TITLE
Ugly scrollbar if too many tabs

### ISSUE THREAD

**Issue by burnoutberni** [PalmerAL/min#70]
If there's too many tabs in the tab bar, it becomes scrollable and at least with Arch Linux/Gnome 3 a scrollbar is displayed.
![screenshot from 2016-04-18 23-00-31](https://cloud.githubusercontent.com/assets/1640933/14619877/fe3f7776-05b9-11e6-899b-a13d549c4bb7.png)

**Comment by burnoutberni** [comment]
PR is one possible fix, maybe one could restyle the scrollbar instead, so it would be more obvious that you can scroll here and yet visually appealing. Dunnå.

**Comment by PalmerAL** [comment]
> maybe one could restyle the scrollbar instead, so it would be more obvious that you can scroll here and yet visually appealing

That's probably a better solution.

**Comment by burnoutberni** [comment]
I played around a bit with the styling and came up with this but it still has (at least) two problems:

* You can't really see it on pages with dark (or even black) tab bars, e.g. GitHub
* On pages like DDG, where the tab bar is the same color as the page background at the top border, it looks a bit crappy.

Do you have any suggestions?

```
.tab-group #tabs::-webkit-scrollbar {
	height: 0.2em;
}
.tab-group #tabs::-webkit-scrollbar-track {
	display: none;
}
.tab-group #tabs::-webkit-scrollbar-thumb {
	background-color: rgba(0,0,0,0.3);
}
```

**Comment by PalmerAL** [comment]
I like the design in general, but it seems like it has a lot of bugs compared to the native scrollbar.

Two more issues:

* The scrollbar affects the height of the tab, instead of floating on top. This leads to bugs like below, where there is a gap between the tab background and the bottom border:

<img width="67" alt="screen shot 2016-04-19 at 8 49 49 pm" src="https://cloud.githubusercontent.com/assets/10314059/14661086/7a91601c-0670-11e6-8b78-08da7173bed7.png">

* The vertical scrollbar in expanded tab mode is broken.

For pages with dark backgrounds, a ```dark-theme``` class is added to the body, so you could change the scrollbar color to white for those pages.

I'll try to think of a solution to the 2nd issue over the next few days.

**Comment by jkanarek** [comment]
@PalmerAL We already have the tab management code, so maybe something there. Could also revert to favicon when the tabs get too small to display text.

**Comment by burnoutberni** [comment]
@PalmerAL I've updated #76. This should fix the ```dark-theme``` and the gap issue, and since the expanded tab view has been replaced your second issue is solved as well.
